### ISSUE TITLE
Does not compile with lazarus-1.6.0

### ISSUE THREAD

**Issue by TheChymera** [neurolabusc/MRIcron#1]
I cannot get MRIcron to compile with lazarus-1.6.0, as detailed [here](https://github.com/gentoo-science/sci/issues/596#issuecomment-188657084). The full build log can be seen [under this link](https://bpaste.net/show/a533095d00ee).

What I think is the crux of it, is that it tries to write outside of the build path - though I may be mistaken and this might just be seen as a consequence of some other issue. Can you help me get your software to compile?

**Comment by neurolabusc** [comment]
It appears you are using Lazarus 1.6 but have fpc 2.6.4. That version of Lazarus requires fpc 3.0.0 and fpm-src 3.0.0. Can I suggest you install those and launch the graphical IDE ("startlazarus"). Next try to compile some of the example projects that come with Lazarus, if you have problems report it to the community (http://mantis.freepascal.org/my_view_page.php).

I can happily compile micron with the command 
  lazbuild ./mricron.lpr
On OSX I can compile to the Carbon or Cocoa widget sets, on Windows I compile to the native Windows API. On Linux I can compile to the GTK2 API.

I am unable to compile to the GTK3 API because all of our Linux boxes run Centos 6
  http://distrowatch.com/table.php?distribution=centos
this is required to run the GPU-accelerated versions of FSL
  http://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation
Scientists tend to be steer clear of the bleeding edge of Linux development. As I understand it, people with GTK3 distros can run GTK2 binaries fine, but the reverse is not true.
