### ISSUE TITLE
dcm2nii issue on MacOSX 10.15.7 (Catalina)

### ISSUE THREAD

**Issue by arswitze** [neurolabusc/MRIcron#16]
I am unable to execute the dcm2nii using Lazarus. I am running MacOSX 10.15.7 (Catalina). I have dcm2niix but a clinica imaging pipeline requires both dcm2nii and dcm2niix to run. Any suggestions for how I can get dcm2nii to work on Catalina?

Thank you

**Comment by neurolabusc** [comment]
I have uploaded a notarized macOS installer for dcm2nii. The file is named [dcm2nii_macOS_obsolete_20201102.pkg](https://github.com/neurolabusc/MRIcron/releases/tag/v1.0.20190902). This will install dcm2nii v1.0.20201102 in /usr/local/bin/dcm2nii. I **strongly** discourage anyone from using this software. Development moved from dcm2nii to dcm2niix six years ago. The DICOM standard has changed a lot since than. I would only recommend this tool for converting [proprietary MR formats](https://www.dclunie.com/medical-image-faq/html/part4.html) that predate DICOM. 

MRIcron is open source, and you are free to maintain, extend or improve this code in any way you want. I am a lecturer and full time scientist, with limited resources. I am investing my time on modern tools. I urge you to consider updating your scripts to leverage the benefits of dcm2niix. There will be unintended consequences if dcm2nii is applied to variations of the DICOM format that were introduced after development ceased.
